<dwarvern-female> ::= '"Name": "'<dwarvern-female-first-name>' '<dwarvern-clan>'", "Gender": "Female", "Race": "Dwarf"'

<dwarvern-male> ::= '"Name": "'<dwarvern-male-first-name>' '<dwarvern-clan>'", "Gender": "Male", "Race": "Dwarf"'

<dwarvern-female-first-name> ::= 'Anbera' | 'Artin' | 'Audhild' | 'Balifra' | 'Barbena' | 'Bardryn' | ' Bolhild' | 'Dagnal' | 
                                'Dariff' | 'Delre' | 'Diesa' | 'Eldeth' | 'Eridred' | 'Falkrunn' | 'Fallthra' | 'Finellen' | 
                                'Gillydd' | 'Gunnloda' | 'Gurdis' | 'Helgret' | 'Helja' | 'Hlin' | 'Ilde' | 'Jarana' | 'Kathra' | 
                                'Kilia' | 'Kristryd' | 'Liftrasa' | 'Marastyr' | 'Mardred' | 'Morana' | 'Nalaed' | 'Nora' | 
                                'Nurkara' | 'Oriff' | 'Ovina' | 'Riswynn' | 'Sanni' | 'Therlin' | 'Thodris' | 'Torbera' | 'Tordrid' | 
                                'Torgga' | 'Urshar' | 'Valida' | 'Vistra' | 'Vonana' | 'Werydd' | 'Whurdred' | 'Yurgunn'

<dwarvern-male-first-name> ::=  'Adrik' | 'Alberich' | 'Baern' | 'Barendd' | 'Beloril' | 'Brottor' | 'Dain' | 'Dalgal' | 'Darrak' | 
                                'Delg' | 'Duergath' | 'Dworic' | 'Eberk' | 'Einkil' | 'Elaim' | 'Erias' | 'Fallond' | 'Fargrim' | 
                                'Gardain' | 'Gilthur' | 'Gimgen' | 'Gimurt' | 'Harbek' | 'Kildrak' | 'Kilvar' | 'Morgran' | 'Morkral' | 
                                'Nalral' | 'Nordak' | 'Nuraval' | 'Oloric' | 'Olunt' | 'Orsik' | 'Oskar' | 'Rangrim' | 'Reirak' | 
                                'Rurik' | 'Taklinn' | 'Thoradin' | 'Thorin' | 'Thradal' | 'Tordek' | 'Traubon' | 'Travok' | 'Ulfgar' | 
                                'Uraim' | 'Veit' | 'Vonbin' | 'Vondal' | 'Whurbin'

<dwarvern-clan> ::= 'Aranore' | 'Balderk' | 'Battlehammer' | 'Bigtoe' | 'Bloodkith' | 'Bofdann' | 'Brawnanvil' | 'Brazzik' | 
                    'Broodfist' | 'Burrowfound' | 'Caebrek' | 'Daerdahk' | 'Dankil' | 'Daraln' | 'Deepdelver' | 'Durthane' | 
                    'Eversharp' | 'Fallack' | 'Fireforge' | 'Foamtankard' | 'Frostbeard' | 'Glanhig' | 'Goblinbane' | 'Goldfinder' | 
                    'Gorunn' | 'Graybeard' | 'Hammerstone' | 'Helcral' | 'Holderhek' | 'Ironfist' | 'Loderr' | 'Lutgehr' | 
                    'Morigak' | 'Orcfoe' | 'Rakankrak' | 'Ruby-Eye' | 'Rumnaheim' | 'Silveraxe' | 'Silverstone' | 'Steelfist' | 
                    'Stoutale' | 'Strakeln' | 'Strongheart' | 'Thrahak' | 'Torevir' | 'Torunn' | 'Trollbleeder' | 'Trueanvil' | 
                    'Trueblood' | 'Ungart' 