<elven-female> ::= '"Name": "'<elven-female-first-name>' '<elven-family-name>'", "Gender": "Female", "Race": "'<elven-races>'"'

<elven-male> ::= '"Name": "'<elven-male-first-name>' '<elven-family-name>'", "Gender": "Male", "Race": "'<elven-races>'"'

<elven-female-first-name> ::= 'Adrie' | 'Ahinar' | 'Althaea' | 'Anastrianna' | 'Andraste' | 'Antinua' | 'Arara' | 
                            'Baelitae' | 'Bethrynna' | 'Birel' | 'Caelynn' | 'Chaedi' | 'Claira' | 'Dara' | 'Drusilia' | 
                            'Elama' | 'Enna' | 'Faral' | 'Felosial' | 'Hatae' | 'Ielenia' | 'Ilanis' | 'Irann' | 'Jarsali' | 
                            'Jelenneth' | 'Keyleth' | 'Leshanna' | 'Lia' | 'Maiathah' | 'Malquis' | 'Meriele' | 'Mialee' | 
                            'Myathethil' | 'Naivara' | 'Quelenna' | 'Quillathe' | 'Ridaro' | 'Sariel' | 'Shanairla' | 'Shava' | 
                            'Silaqui' | 'Sumnes' | 'Theirastra' | 'Thiala' | 'Tiaathque' | 'Traulam' | 'Vadania' | 'Valanthe' | 
                            'Valna' | 'Xanaphia'

<elven-male-first-name> ::= 'Adran' | 'Aelar' | 'Aerdeth' | 'Ahvain' | 'Aramil' | 'Arannis' | 'Aust' | 'Azaki' | 'Beiro' | 
                            'Berrian' | 'Caeldrim' | 'Carric' | 'Dayereth' | 'Dreali' | 'Efferil' | 'Eiravel' | 'Enialis' | 
                            'Erdan' | 'Erevan' | 'Fivin' | 'Galinndan' | 'Gennal' | 'Hadarai' | 'Halimath' | 'Heian' | 'Himo' | 
                            'Immeral' | 'Ivellios' | 'Korfel' | 'Lamlis' | 'Laucian' | 'Lucan' | 'Mindartis' | 'Naal' | 'Nutae' | 
                            'Paelias' | 'Peren' | 'Quarion' | 'Riardon' | 'Rolen' | 'Soveliss' | 'Suhnae' | 'Thamior' | 'Tharivol' | 
                            'Theren' | 'Theriatis' | 'Thervan' | 'Uthemar' | 'Vanuath' | 'Varis'

<elven-family-name> ::= 'Aloro' | 'Amakiir' | 'Amastacia' | 'Ariessus' | 'Arnuanna' | 'Berevan' | 'Caerdonel' | 'Caphaxath' | 
                        'Casilltenirra' | 'Cithreth' | 'Dalanthan' | 'Eathalena' | 'Erenaeth' | 'Ethanasath' | 'Fasharash' | 
                        'Firahel' | 'Floshem' | 'Galanodel' | 'Goltorah' | 'Hanali' | 'Holimion' | 'Horineth' | 'Iathrana' | 
                        'Ilphelkiir' | 'Iranapha' | 'Koehlanna' | 'Lathalas' | 'Liadon' | 'Meliamne' | 'Mellerelel' | 'Mystralath' | 
                        'Naïlo' | 'Netyoive' | 'Ofandrus' | 'Ostoroth' | 'Othronus' | 'Qualanthri' | 'Raethran' | 'Rothenel' | 
                        'Selevarun' | 'Siannodel' | 'Suithrasas' | 'Sylvaranth' | 'Teinithra' | 'Tiltathana' | 'Wasanthi' | 
                        'Withrethin' | 'Xiloscient' | 'Xistsrith' | 'Yaeldrin'

<elven-races> ::= <high-elf> | <wood-elf> | <dark-elf>

<high-elf> ::= 'Sun Elf (High Elf)' | 'Moon Elf (High Elf)'

<wood-elf> ::= 'Wood Elf'

<dark-elf> ::= 'Drow (Dark Elf)'