<human-female> ::= '"Name": "'<human-female-first-name>'", "Gender": "Female", "Race": "'<human-races>'"'

<human-male> ::= '"Name": "'<human-male-first-name>'", "Gender": "Male", "Race": "'<human-races>'"'

<human-female-first-name> ::= 'Adelaide' | 'Agatha' | 'Agnes' | 'Aife' | 'Aina' | 'Alane' | 'Alice' | 'Aline' | 'Anne' | 'Ardena' | 
                            'Arienh' | 'Avelina' | 'Avice' | 'Beatha' | 'Beatrice' | 'Birgit' | 'Briann' | 'Caomh' | 'Cara' | 'Cecily' | 
                            'Cinnia' | 'Cordelia' | 'Deheune' | 'Divone' | 'Donia' | 'Doreena' | 'Egelina' | 'Eleanor' | 'Elizabeth' | 
                            'Ella' | 'Eloise' | 'Elsha' | 'Elysande' | 'Emeny ' | 'Emma' | 'Emmeline' | 'Enid' | 'Ermina' | 'Ethne' | 
                            'Eva' | 'Evelina' | 'Fianna' | 'Galiena' | 'Genevieve' | 'Geva' | 'Gilda' | 'Giselle' | 'Gitta' | 'Grania' | 
                            'Griselda' | 'Gwyndolin' | 'Hadwisa' | 'Helen' | 'Herleva' | 'Hugolina' | 'Ida' | 'Idelisa' | 'Isabella' | 
                            'Isolde' | 'Jacoba' | 'Jane' | 'Joan' | 'Juliana' | 'Katherine' | 'Keelin' | 'Kennocha' | 'Lavena' | 
                            'Lesley' | 'Linnette' | 'Lyonesse ' | 'Mabina' | 'Margery' | 'Marvina' | 'Mary' | 'Matilda' | 'Mavis' | 
                            'Maynild' | 'Millicent' | 'Mirna' | 'Morgan' | 'Muriel' | 'Nareena' | 'Oriana' | 'Oriel' | 'Regan' | 
                            'Rohesia' | 'Ronat' | 'Rosalind' | 'Rosamund' | 'Rowena' | 'Sarah' | 'Selma' | 'Susannah' | 'Sybil' | 
                            'Ula' | 'Venetia' | 'Williamina' | 'Wynne' | 'Yseult' | 'Yvonne'

<human-male-first-name> ::= 'Adam' | 'Adelard' | 'Airell' | 'Airic' | 'Alan' | 'Aldous' | 'Anghus' | 'Anselm' | 'Aodh' | 'Arnold' | 
                            'Bardon' | 'Bearacb' | 'Bernard' | 'Bertram' | 'Bevyn' | 'Boden' | 'Bran' | 'Brasil' | 'Bredon' | 'Brian' | 
                            'Bricriu' | 'Bryant' | 'Cadman ' | 'Caradoc' | 'Cedric' | 'Charles' | 'Clerebold' | 'Conalt' | 'Conchobar' | 
                            'Condon' | 'Conrad' | 'Darcy' | 'Devin' | 'Diggory' | 'Dillion' | 'Donaghy' | 'Donall' | 'Drogo' | 'Duer' | 
                            'Eghan' | 'Everard' | 'Ewyn' | 'Ferghus' | 'Frederick' | 'Galvyn' | 'Geoffrey' | 'Gerald' | 'Gilbert' | 
                            'Gildas' | 'Godfrey ' | 'Gunter' | 'Guy' | 'Harvey' | 'Henry' | 'Heward' | 'Hubert' | 'Hugh' | 'Iden' | 
                            'Irven' | 'Jocelyn' | 'John' | 'Karney' | 'Kayne' | 'Kelvyn' | 'Kunsgnos' | 'Lance' | 'Leigh' | 'Maccus' | 
                            'Manfred' | 'Miles' | 'Moryn' | 'Neale' | 'Nicholas' | 'Norman' | 'Odo' | 'Owyn' | 'Percival' | 'Peter' | 
                            'Pryderi' | 'Ralf' | 'Randal' | 'Raymond' | 'Reaghan' | 'Reynard' | 'Richard' | 'Robert' | 'Roger' | 
                            'Roland' | 'Rolf' | 'Simon' | 'Taliesin' | 'Theobald' | 'Theodoric' | 'Thomas' | 'Tiernay' | 'Timm' | 
                            'Turi ' | 'William' | 'Wymar'

<human-races> ::= 'Human'

