name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: RUSTFLAGS="-C target-cpu=native" cargo build --verbose --release
    - name: Docker Image Build
      run: docker buildx build --platform=linux/arm64 --push -t r0ck3t/procedural-npc:latest .
