name: Rust

on: [push]

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Release
      run: cargo build --verbose --release
    - name: Login to Docker Repository
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_URL: ${{ secrets.DOCKER_URL }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_URL
