name: Rust

on: [push]

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Release
      run: cargo build --verbose --release
