name: Rust

on: [push]

jobs:
  Testing:
    name: Testing
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  Containerize:
    name: Containerize
    needs: Testing
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    # - name: Build Release
    #   run: cargo build --verbose --release
    - name: Build Release
      run: python3 build_all.py
    - name: Login to Docker Repository
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_URL: ${{ secrets.DOCKER_URL }}
      run: img login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_URL
    - name: Build Docker Container
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_REPO_NAME: ${{ secrets.DOCKER_REPO_NAME }}
      run: img build -t $DOCKER_USERNAME/$DOCKER_REPO_NAME:$GITHUB_SHA .
    - name: Tag Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_REPO_NAME: ${{ secrets.DOCKER_REPO_NAME }}
      run: img tag $DOCKER_USERNAME/$DOCKER_REPO_NAME:$GITHUB_SHA $DOCKER_USERNAME/$DOCKER_REPO_NAME:latest
    - name: Push Image to Repository
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_REPO_NAME: ${{ secrets.DOCKER_REPO_NAME }}
      run: img push $DOCKER_USERNAME/$DOCKER_REPO_NAME
    - name: Logout of Docker Repository
      run: img logout
  
  Deploy:
    name: Deploy
    needs: Containerize
    runs-on: self-hosted

    steps:
    - uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
    - name: Get Nodes
      run: kubectl get nodes