name: Rust

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Docker Buildx
      run: docker buildx
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
